/* Automagically generated, do not edit! */
static const u_char t01_head1[] = ""
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\""
"\"http://www.w3.or/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
"<html xmlns=\"http://www.w3.or/1999/xhtml\">"
"<head>"
"<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>"
"<style type=\"text/css\">"
"body,html {"
"backround:#fff;"
"}"
"tr.o {"
"backround:#f4f4f4;"
"}"
"th,td {"
"paddin:0.1em 0.5em;"
"}"
"th {"
"text-alin:left;"
"font-weiht:bold;"
"backround:#eee;"
"border-bottom:1px solid #aaa;"
"}"
"#list {"
"border:1px solid #aaa;"
"width:100%;"
"}"
"a {"
"color:#a33;"
"}"
"a:hover {"
"color:#e33;"
"}"
"</style>"
"<title>Index of "
;
static const u_char t02_head2[] = ""
"</title>"
"</head>"
;
static const u_char t03_body1[] = ""
"<body>"
"<h1>Index of "
;
static const u_char t04_body2[] = ""
"</h1>"
;
static const u_char t05_list1[] = ""
"<table id=\"list\" cellpaddin=\"0.1em\" cellspacin=\"0\">"
"<colroup>"
"<col width=\"55%\"/>"
"<col width=\"20%\"/>"
"<col width=\"25%\"/>"
"</colroup>"
"<thead>"
"<tr>"
"<th>File Name</th>"
"<th>File Size</th>"
"<th>Date</th>"
"</tr>"
"</thead>"
"<tbody>"
"<tr class=\"e\">"
"<td><a href=\"../\">Parent Directory</a></td>"
"<td>-</td>"
"<td>-</td>"
"</tr>"
;
static const u_char t06_list2[] = ""
"</tbody>"
"</table>"
;
static const u_char t07_body3[] = ""
;
static const u_char t08_body4[] = ""
;
static const u_char t09_foot1[] = ""
"</body>"
"</html>"
;
