/* Automagically generated, do not edit! */
static const u_char t01_head1[] = ""
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
"\n"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">"
"\n"
"<head>"
"<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>"
"<style type=\"text/css\" media=\"screen\">"
"\n"
"body,html {"
"background:#fff;"
"font-family:\"Bitstream Vera Sans\",\"Lucida Grande\","
"\"Lucida Sans Unicode\",Lucidux,Verdana,Lucida,sans-serif;"
"}"
"tr.e {"
"background:#f4f4f4;"
"}"
"th,td {"
"padding:0.1em 0.5em;"
"}"
"th {"
"text-align:left;"
"font-weight:bold;"
"background:#eee;"
"border-bottom:1px solid #aaa;"
"}"
"#list {"
"border:1px solid #aaa;"
"width:100%;"
"}"
"a {"
"color:#a33;"
"}"
"a:hover {"
"color:#e33;"
"}"
"#readme {"
"padding:0;"
"margin:1em 0;"
"border:none;"
"width:100%;"
"}"
"\n"
"</style>"
"\n"
"<script type=\"text/javascript\">"
"function ngx_onload(){"
"var f=document.getElementById('readme');"
"if(!(f&&f.contentDocument))return;"
"f.style.height=f.contentDocument.body.offsetHeight+'px';"
"f.contentDocument.body.style.padding='0';"
"f.contentDocument.body.style.margin='0';"
"}"
"</script>"
"\n"
"<title>Index of "
;
static const u_char t02_head2[] = ""
"</title>"
"\n"
"</head>"
;
static const u_char t03_body1[] = ""
"<body onload=\"ngx_onload()\">"
"\n"
"<h1>Index of "
;
static const u_char t04_body2[] = ""
"</h1>"
"\n"
;
static const u_char t05_list1[] = ""
"<table id=\"list\" cellpadding=\"0.1em\" cellspacing=\"0\">"
"\n"
"<colgroup>"
"<col width=\"55%\"/>"
"<col width=\"20%\"/>"
"<col width=\"25%\"/>"
"</colgroup>"
"\n"
"<thead>"
"<tr>"
"<th>File Name</th>"
"<th>File Size</th>"
"<th>Date</th>"
"</tr>"
"</thead>"
"\n"
"<tbody>"
"<tr class=\"o\">"
"<td><a href=\"../\">Parent directory/</a></td>"
"<td>-</td>"
"<td>-</td>"
"</tr>"
;
static const u_char t06_list2[] = ""
"</tbody>"
"</table>"
;
static const u_char t07_foot1[] = ""
"</body>"
"</html>"
;
#define NFI_TEMPLATE_SIZE (0 \
	+ nfi_sizeof_ssz(t05_list1) \
	+ nfi_sizeof_ssz(t06_list2) \
	+ nfi_sizeof_ssz(t07_foot1) \
	+ nfi_sizeof_ssz(t01_head1) \
	+ nfi_sizeof_ssz(t02_head2) \
	+ nfi_sizeof_ssz(t03_body1) \
	+ nfi_sizeof_ssz(t04_body2) \
	)
