#! /bin/bash
#
# preamble
# Copyright (C) 2016 Adrian Perez <aperez@igalia.com>
#
# Distributed under terms of the MIT license.
#

function fail () {
	printf "(FF) "
	printf "$@"
	exit 1
} 1>&2

function warn () {
	printf "(WW)"
	printf "$@"
} 1>&2
